from __future__ import annotations

from pathlib import Path

APP_NAME = "Palabra Zoom Bridge"
__version__ = "0.3.36"
APP_VERSION = __version__
CONFIG_PATH = Path("config.toml")
LOG_DIR = Path("logs")
CABLE_ROUTE_LOG_PATH = LOG_DIR / "cable_route.log"
LAST_ERROR_LOG_PATH = LOG_DIR / "last_error.txt"
SESSION_URL = "https://api.palabra.ai/session-storage/session"
SESSIONS_URL = "https://api.palabra.ai/session-storage/sessions"
DEFAULT_ZOOM_SPEAKER_DEVICE = "CABLE-B Input"
DEFAULT_ZOOM_MIC_DEVICE = "CABLE-A Output"
DEFAULT_END_WHEN_ZOOM_MEETING_ENDS = True
DEFAULT_ZOOM_MEETING_TITLE_PATTERNS = (
    "Zoom Meeting",
    "Zoom Webinar",
)
DEFAULT_ZOOM_MEETING_CHECK_SECONDS = 2.0
DEFAULT_ZOOM_MEETING_END_GRACE_SECONDS = 15.0
DEFAULT_APP_MODE = "cable"
APP_MODES = {"cable", "sdk-probe"}
DEFAULT_ZOOM_SDK_DISPLAY_NAME = "Palabra SDK Probe"
DEFAULT_ZOOM_SDK_PROBE_SECONDS = 10.0
DEFAULT_ZOOM_SDK_OUTPUT_WAV = "debug/zoom_sdk_probe.wav"
DEFAULT_ZOOM_SDK_SAMPLE_RATE = 48000
DEFAULT_ZOOM_SDK_CHANNELS = 1
DEFAULT_ZOOM_SDK_ADAPTER_MODULE = ""
DEFAULT_ZOOM_SDK_ADAPTER_COMMAND = ""
DEFAULT_ZOOM_SDK_ADAPTER_ARGS = ()
DEFAULT_ZOOM_SDK_ROOT = ""
DEFAULT_ZOOM_SDK_DRY_RUN = False
DEFAULT_DEVICE_RATE = 48000
DEFAULT_API_RATE = 24000
DEFAULT_CHANNELS = 1
PALABRA_OUTPUT_RATE = 24000
PALABRA_OUTPUT_CHANNELS = 1
DEFAULT_DEVICE_CHANNELS = 2
DEFAULT_CHUNK_MS = 320
DEFAULT_INPUT_BLOCK_MS = 50
DEFAULT_PLAYBACK_BUFFER_MS = 500
DEFAULT_PHRASE_START_BUFFER_MS = 1800
DEFAULT_PLAYBACK_MAX_BUFFER_MS = 5000
DEFAULT_STARTUP_DELAY = 0.0
DEFAULT_TASK_READY_TIMEOUT_SECONDS = 30.0
DEFAULT_TASK_POLL_SECONDS = 2.0
DEFAULT_END_TASK_EOS_TIMEOUT_SECONDS = 2.0
DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT_SECONDS = 6.0
DEFAULT_PLAYBACK_DRAIN_TIMEOUT_SECONDS = 30.0
DEFAULT_RAW_PALABRA_PLAYBACK = False
DEFAULT_OUTPUT_GAIN = 0.55
DEFAULT_OUTPUT_PEAK_LIMIT = 0.65
DEFAULT_SEGMENT_CONFIRMATION_SILENCE_THRESHOLD = 0.7
DEFAULT_ONLY_CONFIRM_BY_SILENCE = False
DEFAULT_SENTENCE_SPLITTER_ENABLED = True
DEFAULT_PALABRA_TRANSLATE_PARTIALS = True
DEFAULT_PALABRA_DESIRED_QUEUE_LEVEL_MS = 5000
DEFAULT_PALABRA_MAX_QUEUE_LEVEL_MS = 20000
DEFAULT_PALABRA_AUTO_TEMPO = True
DEFAULT_PALABRA_MIN_TEMPO = 1.0
DEFAULT_PALABRA_MAX_TEMPO = 1.45
DEFAULT_TEST_SECONDS = 3.0
DEFAULT_TEST_VOLUME = 0.5
DEFAULT_RECORD_DEBUG_MP3 = False
DEFAULT_DEVICE_PROBE_SECONDS = 0.15
PLAYBACK_BUFFER_STEP_MS = 500
PLAYBACK_ACTIVE_UNDERRUN_STEP_MS = 200
PLAYBACK_BUFFER_RELAX_SECONDS = 30.0
PLAYBACK_SILENCE_RMS = 120.0
PLAYBACK_START_LOOKAHEAD_MS = 2500
PLAYBACK_CATCHUP_TARGET_MS = 1200
PLAYBACK_CATCHUP_FULL_BACKLOG_MS = 4000
DEFAULT_PLAYBACK_TEMPO = 1.0
DEFAULT_PLAYBACK_MAX_LOCAL_TEMPO = 1.06
DEFAULT_PLAYBACK_TEMPO_ALGORITHM = "resample"
PLAYBACK_TEMPO_ALGORITHMS = {"resample", "rubberband"}
TEMPO_PREPROCESS_MIN_MS = 700
DEFAULT_PLAYBACK_FADE_MS = 5
DEFAULT_IDLE_NOISE_AMPLITUDE = 96
BLOCKED_HOSTAPIS = {"Windows WASAPI"}
DEFAULT_HOSTAPI_PREFERENCE = (
    "Windows DirectSound",
    "MME",
    "Windows WDM-KS",
)
DEFAULT_SOURCE_LANGUAGE = "es"
DEFAULT_TARGET_LANGUAGE = "de"
ES_CONTINUOUS = 0x80000000
ES_DISPLAY_REQUIRED = 0x00000002
ES_SYSTEM_REQUIRED = 0x00000001
LANGUAGE_NAMES = {
    "ar": "Arabic",
    "cs": "Czech",
    "de": "German",
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "nl": "Dutch",
    "pl": "Polish",
    "pt": "Portuguese",
    "ru": "Russian",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "zh": "Chinese",
}
